### ISSUE TITLE
pip install snorkel-lite is broken by recent Werkzeug==1.0.0

### ISSUE THREAD

**Issue by alfa07** [logv/snorkel#46]
With version 1.0.0 of Werkzeug I am getting:
```
[I] ➜ PORT=2333 snorkel.frontend
Traceback (most recent call last):
  File "/data/home/msokolov/dev/snorkel-db/penv/bin/snorkel.frontend", line 6, in <module>
    import snorkel
  File "/data/home/msokolov/dev/snorkel-db/penv/lib/python2.7/site-packages/snorkel/__init__.py", line 3, in <module>
    from . import main
  File "/data/home/msokolov/dev/snorkel-db/penv/lib/python2.7/site-packages/snorkel/main.py", line 11, in <module>
    from . import web, models
  File "/data/home/msokolov/dev/snorkel-db/penv/lib/python2.7/site-packages/snorkel/web.py", line 24, in <module>
    from werkzeug.contrib.fixers import ProxyFix
ImportError: No module named contrib.fixers
```
Everything is fine with version 0.16.1

**Comment by okayzed** [comment]
I will pin the version, thank you!

**Comment by okayzed** [comment]
Pinned in 0.0.29
